### ISSUE TITLE
请问用这个替换了镜像中的efi文件夹后

### ISSUE THREAD

**Issue by CaoGongHui** [wdubaiyu/Hackintosh-Dell-XPS-9380#1]
在选择磁盘安装后，出现，验证完整性错误，无法将文件拷贝到磁盘里面，试过修改时间，没有链接网络但是不起作用，请问您知道如何解决吗

**Comment by wdubaiyu** [comment]
建议看下时间是否修改成功，终端输入 date查看当前时间。或者使用BIOS更改时间后再进行安装，最后阶段会提示安装失败，不必理会。可以直接进入系统。如果还是不行请联系QQ：1192151471 验证填写 9380黑苹果
