### ISSUE TITLE
怎么飞线换网卡呢

### ISSUE THREAD

**Issue by Yueling5556** [wdubaiyu/Hackintosh-Dell-XPS-9380#11]
型号为XPS13 9370 同板载网卡
想问问怎么通过飞线安装网卡呢 原装网卡需要拆吗
谢谢了

**Comment by wdubaiyu** [comment]
必须拆，线接在原来的网卡焊点上。和8265一样的点位

**Comment by Yueling5556** [comment]
已经找之前那个提issue的人去问过了，寄给他去换了
现在想再问个问题
xps9370 i7-8550u可以用你的clover装吗
