### ISSUE TITLE
XPS13 9370是否可以用你的clover

### ISSUE THREAD

**Issue by Yueling5556** [wdubaiyu/Hackintosh-Dell-XPS-9380#12]
这两个机子就CPU不一样，网卡我也飞线换了你的同款了
发邮件给您了，并没有回复

**Comment by wdubaiyu** [comment]
9370 我没有啊，并不知道。主板是一样的可能bios不一样而已。4k屏幕的配置和1080p 显卡配置应该不一样。声卡，和触摸板是一样的。9370github上有一个不知道你能用不

**Comment by Yueling5556** [comment]
我试试你的efil吧，cpu代数是一样的
现在efil只适配bigsur11.2吗

**Comment by Yueling5556** [comment]
这个还是clover引导吗
不是opencore吗
