### ISSUE TITLE
无法引导

### ISSUE THREAD

**Issue by Yueling5556** [wdubaiyu/Hackintosh-Dell-XPS-9380#13]
![DCD675BA-6218-45C5-ACA6-2B0A79F3A53E](https://user-images.githubusercontent.com/61104401/132955149-e3522fb9-4105-47a1-8f9a-a6b00545935b.jpeg)
ssdt导致触摸板问题无法引导

**Comment by wdubaiyu** [comment]
qq 1192151471

**Comment by Yueling5556** [comment]
> qq 1192151471

搜不到 好像没开搜索

**Comment by wdubaiyu** [comment]
发你的

**Comment by Yueling5556** [comment]
> 发你的

1935551909
