### ISSUE TITLE
请问该版本适用于9370吗？或者作者有Clover的EFI吗？

### ISSUE THREAD

**Issue by loveXMTX** [wdubaiyu/Hackintosh-Dell-XPS-9380#2]
或者作者有Clover的EFI吗？我想去试试，一直都没有找到很合适的EFI，白装了个系统，好多都驱动不了。。。

**Comment by wdubaiyu** [comment]
这个不用用吗？https://github.com/jieelin/XPS9370-Hackintosh
clover在这里
https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/tree/clover

**Comment by loveXMTX** [comment]
> 这个不用用吗？https://github.com/jieelin/XPS9370-Hackintosh
> clover在这里
> https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/tree/clover

这个作者很久没更新了，目前无法安装，而且手势、音频、摄像头、睡眠没办法驱动，我实在tonymacx86找的。。。

**Comment by wdubaiyu** [comment]
那你试一试我的那个clover吧。我也没有9370帮不上忙

**Comment by loveXMTX** [comment]
感谢！
