### ISSUE TITLE
4k60hz 睡眠唤醒触摸板问题 雷电3 电源管理 问题请教

### ISSUE THREAD

**Issue by tianfire** [wdubaiyu/Hackintosh-Dell-XPS-9380#3]
您好，感谢您的efi，现有以下问题请教
1. 9380的内置4K屏无法4K60HZ 只有48HZ
2. 睡眠唤醒触摸板和触控屏失效的问题如何解决，是否屏蔽触摸屏后可保证触摸板不会在睡眠唤醒后失效
3. 雷电3驱动是否可用 是否可实现热插拔
4. 电源管理目前只有3个选项(不影响使用)
谢谢

**Comment by wdubaiyu** [comment]
1、第一个应该是缩放引起的，OC下确实有这个问题尝试把ig-platform-id 修改为09009B3E
2、第二个问题已经全面解决了最近抽时间整理推送。现在你可以按仓库屏蔽触摸屏解决问题。
3、我没有雷电设备无法进行测试，你可以自己搞雷电的bios设备在\_SB.PCI0.RP09.下。
4、电源管理正常的。因为这个机器wifi无法正常工作就只有3项了。
