### ISSUE TITLE
headphone buzzing

### ISSUE THREAD

**Issue by ZOUHIRZED** [wdubaiyu/Hackintosh-Dell-XPS-9380#4]
hi ty for your effort
i have xps 9380 but with intel wifi 9260
i tried your fix for headphone jack combo  but i still getting buzzing sometimes .maybe i didnt understand your explanation of how to use the installer commande  alc fix
sometimes i have to sleep/wake with jack in and out to get it to work with several tries 
can you help me with that (maybe my xps hardware are different ) thanks man.

**Comment by wdubaiyu** [comment]
dump audio codec in Ubuntu
1： cp /proc/asound/card0/codec* . 
2： dmesg | grep snd_hda_codec_realtek > xps9380EffectiveNode.txt
3：Upload here

**Comment by ZOUHIRZED** [comment]
[xps9380EffectiveNode.txt](https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/files/5343487/xps9380EffectiveNode.txt)

**Comment by ZOUHIRZED** [comment]
[codec#0.txt](https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/files/5343493/codec.0.txt)
[codec#2.txt](https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/files/5343494/codec.2.txt)

**Comment by wdubaiyu** [comment]
We have the same codec ，but only the converter stream is different in Node 0x02 and Node 0x03。
My codec is stream=0，your codec is stream=1.

**Comment by ZOUHIRZED** [comment]
ok what need to be done to the fix to get it working
or do i have to go to alc full guide and check (make my own fix )
i believe its this one 
https://osxlatitude.com/forums/topic/11316-how-to-fix-static-noisedistortioncrackling-sound-and-combo-jack-on-laptops/

**Comment by ZOUHIRZED** [comment]
so i did some digging and i think i know how to do it : 
i need to rebuid my own hda-verb with my codec in hda-tools folder and use the generated hda-verb instead of yours ( is this even correct or do i have to make other modification also to ALCPlugFix 
i have no clue how to rebuild my own fils can please tell how to do so? thanks

**Comment by wdubaiyu** [comment]
My ALCPlugFix used 'hda-verd 0x19 SET_PIN_WIDGET_CONTROL 0x24 '

**Comment by ZOUHIRZED** [comment]
i have   Pin-ctls: 0x24 too at node x19 (Headset Mic Boost Volume) i dont get it we have the same codec yet its not working well sometimes it does though,maybe you can re-explain to me how to install it correctly   

i also have another Node 0x1b Pin-ctls: 0x20 (Headphone Mic Boost Volume)

**Comment by wdubaiyu** [comment]
After installing the system, download the repository and double-click 'ALCPlugFix/alc_fix/install双击自动安装（解决耳机无声）10.15.x.command' to install

**Comment by ZOUHIRZED** [comment]
finally, the fix only worked after I updated to 10.15.7 (with buzzing gone after sleep/wake first try before I had to that many time as I mentioned before) same need to be done when rebooting/sleep while the jack is plug 
just for your info I'm using the latest dell bios update rather than v 1.8 and different cpu (u8665 i7 by the way I generated my own cpufriend and cpufriend provider cause the fan was so loud and modified cfg lock to off in bios extracted) those are the only differences than you wonder why the fix doesn't work pre 10.15.6

**Comment by wdubaiyu** [comment]
My main-board PCB NO is LA-E672P and it 8665u is not supported form the schematic diagram。
There may be subtle differences in our machines。

![Snipaste_2020-10-15_12-48-36](https://user-images.githubusercontent.com/9440981/96078457-ef984c00-0ee4-11eb-9a9f-21b40b6632e9.png)

**Comment by ZOUHIRZED** [comment]
can you share your codec dump  (and if possible schematic for future soc wifi change) please thanks.

**Comment by wdubaiyu** [comment]
[AlC299_dmesg.txt](https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/files/5390066/AlC299_dmesg.txt)

[codec#.txt](https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/files/5390069/codec.txt)
![Snipaste_2020-10-16_15-56-57](https://user-images.githubusercontent.com/9440981/96228858-b3d6b280-0fc8-11eb-8946-9c3c82724cdd.png)

**Comment by ZOUHIRZED** [comment]
thanks
