### ISSUE TITLE
飞线更换无线网卡后

### ISSUE THREAD

**Issue by tianfire** [wdubaiyu/Hackintosh-Dell-XPS-9380#5]
您好，我更换了苹果的拆机网卡94360cs2 WiFi 蓝牙都可使用了，同时Airdrop也没问题，但蓝牙时断时好(win下没有问题)，请问是不是更换苹果网卡后需要改动efi的配置啊，请赐教

**Comment by wdubaiyu** [comment]
飞线网卡啊？大神我要膜拜下；这个问题还是等大神教我飞线等我学会来在研究下

**Comment by tianfire** [comment]
把本身的网卡吹掉了 然后飞线了94360cs2 空投啥的都没问题 您这个efi里有关于板载蓝牙设置的东西吗 比如ssdt啥的 还有usb相关的 我是不是得把新蓝牙设置一下啊 因为我这个新蓝牙是走usb的 因为我看您用的是ssdt配置的usb

**Comment by wdubaiyu** [comment]
SSDT-USBX-UIAC.aml 这个定义了usb相关。其他地方没有和usb相关的内容，蓝牙没有其他设置。
建议移除：UVC2FaceTimeHD.kext，NoTouchID.kext 试一试，当然你也可以适用下clover分支下的最新efi测试。

94360cs2放在那个位置的，原来网卡哪里能放下吗？
另外这些线都哪些需要和网卡连接我不太懂。能给个接线原理吗？
![Snipaste_2020-10-15_12-56-11](https://user-images.githubusercontent.com/9440981/96078806-ee1b5380-0ee5-11eb-9347-2d8a215e65a1.png)

**Comment by tianfire** [comment]
![66E635C2-C519-49E0-A85C-72A67526001B](https://user-images.githubusercontent.com/18052782/96272660-ff0cb780-1000-11eb-8e7a-ebdce5688fba.jpeg)
放到这个地方就行 按照下面的连接方式
![C1579E3E-59F3-4731-9A71-C6342479CD1F](https://user-images.githubusercontent.com/18052782/96272890-45faad00-1001-11eb-95d1-07bd45672543.jpeg)
可以加个WX聊详细的方式和注意事项 Bert-9090

**Comment by ZOUHIRZED** [comment]
omg ty this so helpful I will consider desoldering if  my 9260 ac doesn't get the full support from intel airport project

**Comment by Harshmf** [comment]
can you upload a picture of what you did on the inside of your laptop?

please attach some pictures
