### ISSUE TITLE
How did you manage to change your wifi card?

### ISSUE THREAD

**Issue by Harshmf** [wdubaiyu/Hackintosh-Dell-XPS-9380#8]
Please let us know how you changed the wifi card.
it is soldered is what i know

**Comment by ZOUHIRZED** [comment]
check  his closed issues

**Comment by pdj1221** [comment]
同问，请教硬改wifi教程！！！

**Comment by wdubaiyu** [comment]
reference
https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/issues/5#issuecomment-782888264
