### ISSUE TITLE
请问大佬你飞线怎么飞的？

### ISSUE THREAD

**Issue by linianqing** [wdubaiyu/Hackintosh-Dell-XPS-9380#9]
抱歉问一下，飞线具体怎么个飞法、、、然后里面是又接了个m2插槽么，那加上转接卡和网卡，笔记本空间塞得下么？
感谢分享，我是用的9370，也想折腾了飞线，续费了3年全智服务都浪费了，现在过保了打算折腾一下。

**Comment by wdubaiyu** [comment]
不要转接卡，就是用线把主板和苹果的卡连接在一起。weichat dubaiyu
